/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lyy.pg.orcl.view;

import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.UIManager;
import lyy.pg.orcl.model.DBSource;
import lyy.pg.orcl.util.DB;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

/**
 *
 * @author Liu Yuanyuan
 */
public class MainView extends JFrame
{

    private Logger logger = LogManager.getLogger(getClass());
    private ResourceBundle constBundle = ResourceBundle.getBundle("constants");

    private DBSource sourceDB;
    private DBSource targetDB;

    public MainView()
    {
        logger.debug("Enter");
        initComponents();
        setTitle("orcl2pg");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/lyy/pg/orcl/image/orcl2pg.png")));

        cbSourceDB.setModel(new DefaultComboBoxModel(new String[]
        {
            constBundle.getString("sourceDB")
        }));
        cbTargetDB.setModel(new DefaultComboBoxModel(new String[]
        {
            constBundle.getString("targetDB")
        }));

        
        ActionListener dbItemActionListener = new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                dbItemActionPerformed(e);
            }
        };
        cbSourceDB.addActionListener(dbItemActionListener);
        cbTargetDB.addActionListener(dbItemActionListener);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        toolBar = new javax.swing.JToolBar();
        btnMigrate = new javax.swing.JButton();
        btnConvert = new javax.swing.JButton();
        cbSourceDB = new javax.swing.JComboBox();
        cbTargetDB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        toolBar.setRollover(true);

        btnMigrate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lyy/pg/orcl/image/migrator_48px.png"))); // NOI18N
        btnMigrate.setFocusable(false);
        btnMigrate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMigrate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnMigrate);

        btnConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lyy/pg/orcl/image/convert_48px.png"))); // NOI18N
        btnConvert.setFocusable(false);
        btnConvert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConvert.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnConvert);

        cbSourceDB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        toolBar.add(cbSourceDB);

        cbTargetDB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        toolBar.add(cbTargetDB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbItemActionPerformed(ActionEvent e)
    {
        logger.debug(e.getActionCommand());
     
        JComboBox cbb = (JComboBox) e.getSource();
        Object selectedItem = cbb.getSelectedItem();
        if (selectedItem == null)
        {
            return;
        }        
        logger.debug(selectedItem.toString());
        DBConfigDialog dbcDialog = new DBConfigDialog(this, true,
                selectedItem.equals(constBundle.getString("sourceDB")) ? DB.Oracle : DB.PostgreSQL);
        dbcDialog.setLocationRelativeTo(this);
        dbcDialog.setVisible(true);
        if (dbcDialog.getResponse() == 0)
        {
            DBSource db = dbcDialog.getDBSource();
            cbb.addItem(db);
            cbb.setSelectedItem(db);
        }
    }
    

    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName().toString());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            //java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            System.err.println(ex.getMessage());
            ex.printStackTrace(System.out);
        }

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                MainView mainView = new MainView();
                mainView.setLocationRelativeTo(null);
                mainView.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnMigrate;
    private javax.swing.JComboBox cbSourceDB;
    private javax.swing.JComboBox cbTargetDB;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
